const ReleaseActionTypes = {
  RELEASE_REQUEST: "RELEASE_REQUEST",
  RELEASE_SUCCESS: "RELEASE_SUCCESS",
  RELEASE_FAIL: "RELEASE_FAIL",
  RELEASE_TYPE_TOGGLE: "RELEASE_TYPE_TOGGLE",
  OPEN_TRACKLIST: "OPEN_TRACKLIST",
  CLOSE_TRACKLIST: "CLOSE_TRACKLIST",
};

export default ReleaseActionTypes;
